node {
  stage ('Checkout'){
  checkout([
    $class: 'GitSCM',
      branches: [[name: '*/readyMultiBranchPipe/*']],
      userRemoteConfigs: [[
        name: 'origin',
        url: 'git@github.com:bicschneider/test-git-phlow-plugin.git'
      ]],
      extensions: [
        pretestedIntegration(
          gitIntegrationStrategy: accumulated(),
          integrationBranch: 'masterMultiBranchPipe',
          repoName: 'origin')
        ,
        [ $class: 'ChangelogToBranch',
          options: [compareRemote: 'origin', compareTarget: 'masterMultiBranchPipe']
        ]
      ]
    ])
//    try {
//      sh '''
//      if [ -e ./build_failed.md ]; then
//        exit 1
//      fi
//      '''
//    } catch(Exception e) {
//      currentBuild.result = 'UNSTABLE'
//    }
    pretestedIntegrationPublisher()
  }
}
