node {
   // Mark the code checkout 'stage'....
   stage ('Checkout'){

       // Get some code from a GitHub repository
       checkout([
            $class: 'GitSCM',
            branches: [[name: '*/readyPipeSCM/*']],
            userRemoteConfigs: [[
                name: 'origin',
                url: 'git@github.com:bicschneider/test-git-phlow-plugin.git'
            ]],
            extensions: [
            [
                $class: 'PretestedIntegrationAsGitPluginExt',
                    gitIntegrationStrategy : [ $class: 'AccumulatedCommitStrategy' ],
                    integrationBranch : 'masterPipeSCM',
                    repoName: 'origin'
            ],[
                $class: 'ChangelogToBranch', options: [compareRemote: 'origin', compareTarget: 'masterPipeSCM']
                ]
            ]
        ])
        try {
            sh '''
            if [ -e ./build_failed.md ]; then
              exit 1
            fi
            '''
        } catch(Exception e) {
            currentBuild.result = 'UNSTABLE'
        }
        step([$class: 'PretestedIntegrationPostCheckout'])
   }
}
